# Generated by Django 4.1.7 on 2023-03-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='session_name',
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
